remote_theme: pages-themes/hacker@v0.2.0
title: ["EasyNN: Demystifying Neural Networks"]
description: [Unlock the world of neural networks with EasyNN—a user-friendly C++ library that transforms theoretical understanding into practical implementation.]
logo: /assets/img/logo.png
